# Generated by Django 4.2.24 on 2025-10-01 05:01

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(max_length=20, unique=True, verbose_name='Número de compra')),
                ('order_date', models.DateField(verbose_name='Fecha de orden')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='Fecha esperada de entrega')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Fecha de recepción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente'), ('received', 'Recibida'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Estado')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('partial', 'Pago Parcial'), ('paid', 'Pagado')], default='pending', max_length=20, verbose_name='Estado de pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Descuento')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Costo de envío')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Persona de contacto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='NIT/RUT')),
                ('payment_terms', models.CharField(blank=True, max_length=100, verbose_name='Términos de pago')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, verbose_name='Número de recibo')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Recibido en')),
                ('notes', models.TextField(blank=True, verbose_name='Notas de recepción')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='purchases.purchase', verbose_name='Compra')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Recibo de compra',
                'verbose_name_plural': 'Recibos de compra',
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo unitario')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5, verbose_name='% IVA')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IVA')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Producto')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Item de compra',
                'verbose_name_plural': 'Items de compra',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='purchases.supplier', verbose_name='Proveedor'),
        ),
    ]
