# Generated by Django 4.2.24 on 2025-09-30 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('report_type', models.CharField(choices=[('sales', 'Ventas'), ('inventory', 'Inventario'), ('products', 'Productos'), ('customers', 'Clientes'), ('financial', 'Financiero')], max_length=20, verbose_name='Tipo de reporte')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('template_data', models.JSONField(verbose_name='Datos del template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Template de reporte',
                'verbose_name_plural': 'Templates de reportes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('frequency', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], max_length=20, verbose_name='Frecuencia')),
                ('email_recipients', models.TextField(verbose_name='Destinatarios de email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Última ejecución')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Próxima ejecución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Programación de reporte',
                'verbose_name_plural': 'Programaciones de reportes',
                'ordering': ['name'],
            },
        ),
    ]
