# Generated by Django 4.2.24 on 2025-09-30 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('customers', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, unique=True, verbose_name='ID de sesión')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=20, verbose_name='Estado')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Efectivo inicial')),
                ('closing_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Efectivo final')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total ventas')),
                ('total_transactions', models.PositiveIntegerField(default=0, verbose_name='Total transacciones')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Abierta en')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cerrada en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='Bodega')),
            ],
            options={
                'verbose_name': 'Sesión POS',
                'verbose_name_plural': 'Sesiones POS',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='POSSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(max_length=20, unique=True, verbose_name='Número de venta')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('mixed', 'Mixto')], max_length=20, verbose_name='Método de pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('iva_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('barcode_scanned', models.CharField(blank=True, max_length=50, verbose_name='Código de barras escaneado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada en')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Cliente')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='pos.possession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Venta POS',
                'verbose_name_plural': 'Ventas POS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('iva_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% IVA')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('iva_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.possale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Item de venta POS',
                'verbose_name_plural': 'Items de venta POS',
                'unique_together': {('sale', 'product')},
            },
        ),
    ]
