# Generated by Django 4.2.24 on 2025-09-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_possale_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
    ]
