# Generated by Django 4.2.24 on 2025-09-30 03:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='normal', max_length=10, verbose_name='Tipo de cliente')),
                ('document_type', models.CharField(max_length=20, verbose_name='Tipo de documento')),
                ('document_number', models.CharField(max_length=20, unique=True, verbose_name='Número de documento')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="El número de teléfono debe tener el formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la dirección')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_default', models.BooleanField(default=False, verbose_name='Dirección por defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Dirección de cliente',
                'verbose_name_plural': 'Direcciones de clientes',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
