# Generated by Django 4.2.24 on 2025-10-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='channel',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('google', 'Google'), ('referral', 'Referido por cliente'), ('walk_in', 'Cliente de tienda física'), ('website', 'Sitio web'), ('email', 'Email'), ('phone', 'Llamada telefónica'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Canal de llegada'),
        ),
    ]
