# Generated by Django 4.2.24 on 2026-01-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'external_id',
                    models.PositiveIntegerField(unique=True, verbose_name='ID Externo'),
                ),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='País')),
                ('iso2', models.CharField(blank=True, max_length=2, null=True, verbose_name='ISO2')),
                ('iso3', models.CharField(blank=True, max_length=3, null=True, verbose_name='ISO3')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('external_id', models.PositiveIntegerField(verbose_name='ID Externo')),
                ('name', models.CharField(max_length=150, verbose_name='Departamento')),
                ('iso2', models.CharField(blank=True, max_length=10, null=True, verbose_name='ISO2')),
                (
                    'country',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='departments',
                        to='customers.country',
                        verbose_name='País',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['country__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('external_id', models.PositiveIntegerField(verbose_name='ID Externo')),
                ('name', models.CharField(max_length=150, verbose_name='Ciudad')),
                (
                    'department',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cities',
                        to='customers.department',
                        verbose_name='Departamento',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['department__country__name', 'department__name', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(
                fields=('country', 'external_id'),
                name='uniq_department_external_id',
            ),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(
                fields=('country', 'name'),
                name='uniq_department_name',
            ),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(
                fields=('department', 'external_id'),
                name='uniq_city_external_id',
            ),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(
                fields=('department', 'name'),
                name='uniq_city_name',
            ),
        ),
    ]
