# Generated by Django 4.2.24 on 2025-10-01 05:29

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo del reporte', max_length=200, verbose_name='Nombre del Reporte')),
                ('report_type', models.CharField(choices=[('USER_ACTIVITY', 'Actividad de Usuario'), ('MODEL_CHANGES', 'Cambios de Modelo'), ('SECURITY_EVENTS', 'Eventos de Seguridad'), ('SYSTEM_EVENTS', 'Eventos del Sistema'), ('CUSTOM', 'Personalizado')], max_length=50, verbose_name='Tipo de Reporte')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('GENERATING', 'Generando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Parámetros utilizados para generar el reporte', verbose_name='Parámetros')),
                ('file_path', models.CharField(blank=True, help_text='Ruta del archivo generado', max_length=500, null=True, verbose_name='Ruta del Archivo')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True, verbose_name='Tamaño del Archivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si el reporte falló', null=True, verbose_name='Mensaje de Error')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Reporte de Auditoría',
                'verbose_name_plural': 'Reportes de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión'), ('VIEW', 'Ver'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar'), ('PRINT', 'Imprimir'), ('EMAIL', 'Enviar Email'), ('CANCEL', 'Cancelar'), ('APPROVE', 'Aprobar'), ('REJECT', 'Rechazar'), ('COMPLETE', 'Completar'), ('TRANSFER', 'Transferir'), ('RECEIVE', 'Recibir'), ('RETURN', 'Devolver'), ('REFUND', 'Reembolsar'), ('DISCOUNT', 'Descuento'), ('PAYMENT', 'Pago'), ('STOCK_ADJUSTMENT', 'Ajuste de Stock'), ('PRICE_CHANGE', 'Cambio de Precio'), ('STATUS_CHANGE', 'Cambio de Estado'), ('PERMISSION_CHANGE', 'Cambio de Permisos'), ('PASSWORD_CHANGE', 'Cambio de Contraseña'), ('PROFILE_UPDATE', 'Actualizar Perfil'), ('SYSTEM_CONFIG', 'Configuración del Sistema'), ('BACKUP', 'Respaldo'), ('RESTORE', 'Restaurar'), ('OTHER', 'Otro')], help_text='Tipo de acción realizada', max_length=50, verbose_name='Acción')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID del objeto afectado', null=True, verbose_name='ID del Objeto')),
                ('object_repr', models.CharField(blank=True, help_text='Representación string del objeto', max_length=200, null=True, verbose_name='Representación del Objeto')),
                ('old_values', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Valores antes del cambio', null=True, verbose_name='Valores Anteriores')),
                ('new_values', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Valores después del cambio', null=True, verbose_name='Valores Nuevos')),
                ('severity', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], default='MEDIUM', help_text='Nivel de severidad del evento', max_length=20, verbose_name='Severidad')),
                ('status', models.CharField(choices=[('SUCCESS', 'Exitoso'), ('FAILED', 'Fallido'), ('PENDING', 'Pendiente'), ('CANCELLED', 'Cancelado')], default='SUCCESS', help_text='Estado del evento', max_length=20, verbose_name='Estado')),
                ('message', models.TextField(blank=True, help_text='Descripción detallada del evento', null=True, verbose_name='Mensaje')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se realizó la acción', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/cliente', null=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, help_text='ID de la sesión', max_length=40, null=True, verbose_name='Clave de Sesión')),
                ('app_label', models.CharField(blank=True, help_text='Nombre de la aplicación Django', max_length=50, null=True, verbose_name='Etiqueta de App')),
                ('model_name', models.CharField(blank=True, help_text='Nombre del modelo Django', max_length=50, null=True, verbose_name='Nombre del Modelo')),
                ('extra_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Información adicional del evento', null=True, verbose_name='Datos Extra')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento en que ocurrió el evento', verbose_name='Fecha de Creación')),
                ('content_type', models.ForeignKey(blank=True, help_text='Tipo de modelo afectado', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó este registro de auditoría', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_audit_user_id_a3c2bc_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'), models.Index(fields=['severity', 'status'], name='audit_audit_severit_9ed2cb_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Si la auditoría está habilitada para este modelo', verbose_name='Habilitado')),
                ('track_fields', models.JSONField(blank=True, default=list, help_text='Lista de campos específicos a auditar (vacío = todos)', verbose_name='Campos a Rastrear')),
                ('exclude_fields', models.JSONField(blank=True, default=list, help_text='Lista de campos a excluir de la auditoría', verbose_name='Campos Excluidos')),
                ('track_creates', models.BooleanField(default=True, help_text='Si rastrear cuando se crean objetos', verbose_name='Rastrear Creaciones')),
                ('track_updates', models.BooleanField(default=True, help_text='Si rastrear cuando se actualizan objetos', verbose_name='Rastrear Actualizaciones')),
                ('track_deletes', models.BooleanField(default=True, help_text='Si rastrear cuando se eliminan objetos', verbose_name='Rastrear Eliminaciones')),
                ('track_views', models.BooleanField(default=False, help_text='Si rastrear cuando se visualizan objetos', verbose_name='Rastrear Visualizaciones')),
                ('severity_level', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], default='MEDIUM', help_text='Nivel de severidad por defecto para este modelo', max_length=20, verbose_name='Nivel de Severidad')),
                ('retention_days', models.PositiveIntegerField(default=365, help_text='Días que mantener los logs antes de eliminarlos', verbose_name='Días de Retención')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('content_type', models.ForeignKey(help_text='Modelo a auditar', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de Contenido')),
            ],
            options={
                'verbose_name': 'Configuración de Auditoría',
                'verbose_name_plural': 'Configuraciones de Auditoría',
                'unique_together': {('content_type',)},
            },
        ),
    ]
