# Generated by Django 4.2.24 on 2025-10-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, help_text='ID del objeto afectado', max_length=255, null=True, verbose_name='ID del Objeto'),
        ),
    ]
