# Generated by Django 4.2.24 on 2025-10-01 05:37

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('pos', '0003_possession_notes'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
        ('orders', '0002_order_order_type'),
        ('audit', '0002_alter_auditlog_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditreport',
            name='report_type',
            field=models.CharField(choices=[('USER_ACTIVITY', 'Actividad de Usuario'), ('MODEL_CHANGES', 'Cambios de Modelo'), ('SECURITY_EVENTS', 'Eventos de Seguridad'), ('SYSTEM_EVENTS', 'Eventos del Sistema'), ('INVENTORY_TRACE', 'Trazabilidad de Inventario'), ('CUSTOM', 'Personalizado')], max_length=50, verbose_name='Tipo de Reporte'),
        ),
        migrations.CreateModel(
            name='InventoryTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Compra'), ('PURCHASE_RECEIPT', 'Recepción de Compra'), ('STOCK_ADJUSTMENT', 'Ajuste de Stock'), ('STOCK_TRANSFER', 'Transferencia'), ('STOCK_TRANSFER_RECEIVE', 'Recepción de Transferencia'), ('SALE', 'Venta'), ('SALE_RETURN', 'Devolución de Venta'), ('DAMAGE', 'Daño'), ('THEFT', 'Robo'), ('EXPIRATION', 'Vencimiento'), ('DONATION', 'Donación'), ('SAMPLE', 'Muestra'), ('OTHER', 'Otro')], help_text='Tipo de movimiento de inventario', max_length=30, verbose_name='Tipo de Movimiento')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado'), ('REJECTED', 'Rechazado')], default='PENDING', help_text='Estado actual del movimiento', max_length=20, verbose_name='Estado')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Cantidad del movimiento (positiva para entrada, negativa para salida)', max_digits=10, verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario del producto en este movimiento', max_digits=10, null=True, verbose_name='Costo Unitario')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Costo total del movimiento', max_digits=12, null=True, verbose_name='Costo Total')),
                ('stock_before', models.DecimalField(decimal_places=2, help_text='Stock disponible antes del movimiento', max_digits=10, verbose_name='Stock Antes')),
                ('stock_after', models.DecimalField(decimal_places=2, help_text='Stock disponible después del movimiento', max_digits=10, verbose_name='Stock Después')),
                ('batch_number', models.CharField(blank=True, help_text='Número de lote del producto', max_length=100, null=True, verbose_name='Número de Lote')),
                ('expiration_date', models.DateField(blank=True, help_text='Fecha de vencimiento del producto', null=True, verbose_name='Fecha de Vencimiento')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el movimiento', null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento en que se creó el movimiento', verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Momento de la última actualización', verbose_name='Fecha de Actualización')),
                ('extra_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Información adicional del movimiento', null=True, verbose_name='Datos Extra')),
                ('order', models.ForeignKey(blank=True, help_text='Orden que originó este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Orden')),
                ('order_item', models.ForeignKey(blank=True, help_text='Item específico de la orden', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderitem', verbose_name='Item de Orden')),
                ('pos_sale', models.ForeignKey(blank=True, help_text='Venta POS que originó este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.possale', verbose_name='Venta POS')),
                ('pos_sale_item', models.ForeignKey(blank=True, help_text='Item específico de la venta POS', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.possaleitem', verbose_name='Item de Venta POS')),
                ('product', models.ForeignKey(help_text='Producto afectado', on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Producto')),
                ('purchase', models.ForeignKey(blank=True, help_text='Compra que originó este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchase', verbose_name='Compra')),
                ('purchase_item', models.ForeignKey(blank=True, help_text='Item específico de la compra', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaseitem', verbose_name='Item de Compra')),
                ('stock_transfer', models.ForeignKey(blank=True, help_text='Transferencia que originó este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocktransfer', verbose_name='Transferencia')),
                ('stock_transfer_item', models.ForeignKey(blank=True, help_text='Item específico de la transferencia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stocktransferitem', verbose_name='Item de Transferencia')),
                ('supplier', models.ForeignKey(blank=True, help_text='Proveedor del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.supplier', verbose_name='Proveedor')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('warehouse', models.ForeignKey(help_text='Bodega donde ocurre el movimiento', on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='Bodega')),
            ],
            options={
                'verbose_name': 'Trazabilidad de Inventario',
                'verbose_name_plural': 'Trazabilidades de Inventario',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'warehouse', 'created_at'], name='audit_inven_product_e1b24b_idx'), models.Index(fields=['movement_type', 'status'], name='audit_inven_movemen_bd9d7a_idx'), models.Index(fields=['created_at'], name='audit_inven_created_97c7d8_idx'), models.Index(fields=['batch_number'], name='audit_inven_batch_n_c6e065_idx'), models.Index(fields=['expiration_date'], name='audit_inven_expirat_60c94d_idx')],
            },
        ),
    ]
