# Generated by Django on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='HomeBannerConfig',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='home_banners/',
                        verbose_name='Imagen banner',
                    ),
                ),
                (
                    'alt_text',
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name='Texto alternativo',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, verbose_name='Activo'),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='Actualizado en',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Configuración Banner Home',
                'verbose_name_plural': 'Configuración Banner Home',
            },
        ),
    ]
