# Generated by Django 4.2.24 on 2025-09-30 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Número de orden')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('pending', 'Pendiente'), ('paid', 'Pagado'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='new', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('cash_on_delivery', 'Contraentrega'), ('bank_transfer', 'Transferencia Bancolombia'), ('addi', 'Addi')], max_length=20, verbose_name='Método de pago')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('iva_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('shipping_address', models.TextField(verbose_name='Dirección de envío')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Ciudad de envío')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='Teléfono de envío')),
                ('shipping_notes', models.TextField(blank=True, verbose_name='Notas de envío')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada en')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagada en')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada en')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregada en')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customers.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('min_weight', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Peso mínimo (kg)')),
                ('max_weight', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Peso máximo (kg)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('estimated_days', models.PositiveIntegerField(default=1, verbose_name='Días estimados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada en')),
            ],
            options={
                'verbose_name': 'Tarifa de envío',
                'verbose_name_plural': 'Tarifas de envío',
                'ordering': ['city', 'min_weight'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('iva_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% IVA')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('iva_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item de orden',
                'verbose_name_plural': 'Items de orden',
                'unique_together': {('order', 'product')},
            },
        ),
    ]
