# Generated by Django 4.2.24 on 2025-09-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('principal', 'Principal'), ('auxiliar', 'Auxiliar')], default='principal', max_length=20, verbose_name='Tipo de orden'),
        ),
    ]
