# Generated by Django 4.1 on 2025-11-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wompi_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia Wompi'),
        ),
        migrations.AddField(
            model_name='order',
            name='wompi_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Wompi'),
        ),
        migrations.AddField(
            model_name='order',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transacción Wompi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Contraentrega'), ('bank_transfer', 'Transferencia Bancolombia'), ('wompi', 'Wompi - Tarjeta de Crédito/Débito'), ('addi', 'Addi')], max_length=20, verbose_name='Método de pago'),
        ),
    ]
