# Generated by Django 4.1 on 2025-11-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_wompi_reference_order_wompi_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WompiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(blank=True, max_length=200, verbose_name='Clave Pública')),
                ('private_key', models.CharField(blank=True, max_length=200, verbose_name='Clave Privada')),
                ('integrity_secret', models.CharField(blank=True, max_length=200, verbose_name='Secreto de Integridad')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox (Pruebas)'), ('production', 'Producción')], default='sandbox', max_length=20, verbose_name='Ambiente')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
            ],
            options={
                'verbose_name': 'Configuración Wompi',
                'verbose_name_plural': 'Configuración Wompi',
            },
        ),
    ]
